on: workflow_dispatch
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: 'Download sdist and wheels artifacts'
        shell: bash
        run: |
          echo "::debug::This is a single-line debug."
          echo "::debug::Multi\nline\debug"
          echo "::notice file=app.js,line=1,col=5,endColumn=7,title=Notice Title::Notice message in one line"
          echo "::notice file=app.js,line=1,col=5,endColumn=7,title=Notice Title::Notice message in \n two lines"
          echo "::warning title=😬Warning Title::🙋Missing semicolon"
          echo "::error file=app.js,line=1,col=5,endColumn=7,title=Error Title::Missing semicolon"
          
          echo "::group::\033[1;38;2;255;255;255;48;2;150;0;170mMy title"
          echo "::debug::This is a single-line debug."
          echo "::debug::Multi\nline\debug"
          echo "::notice file=app.js,line=1,col=5,endColumn=7,title=Notice Title::Notice message in one line"
          echo "::notice file=app.js,line=1,col=5,endColumn=7,title=Notice Title::Notice message in \n two lines"
          echo "::warning file=app.js,line=1,col=5,endColumn=7,title=Warning Title::Missing semicolon"
          echo "::error file=app.js,line=1,col=5,endColumn=7,title=Error Title::Missing semicolon"
          echo "::endgroup::"
      - shell: python
        run: |
          print("::warning title=A Warning From Python::\033[1;38;2;255;255;255;48;2;150;0;170mFirst line........rojgwgwr wrg wr gw rgwr gw rgw rgw g wrigjworijg wr gwirgj  worgjiw rog")
          print("::warning title=A Multiline Warning Title From Python::First line.\nSecond Line.\nThird Line.")
          print("::debug::\033[1;38;2;255;255;255;48;2;150;0;170mA sinle line debug message from python")
          print("::debug::First Xline.\nSecond XLine.\n  XThird Line.\n    Fourth XLine")
          print("::debug::A sinle line debug message from python")
          print("::group::\033[1;38;2;255;255;255;48;2;150;0;170mMy title")
          print("Blah")
          print("::endgroup::")
          print("::group:: ::warning title=A Multiline Warning Title From Python::First line.\nSecond Line.\nThird Line.")
          print("Blah")
          print("::endgroup::")
          print("::group::\n::warning title=A Multiline Warning Title From Python::First line.\nSecond Line.\nThird Line.")
          print("Blah")
          print("::endgroup::")
      - shell: bash
        run: |
          pip install rich
          python -m rich
      - shell: python
        run: |
          print("::debug::Multi\nline\debug")
          print("::debug::::group::title\ngrouup content\n::endgroup::")
          print("::group::title\ngrouup content\n::endgroup::")
          print("""::debug::::group::group name\n::debug::group content\n::debug::::endgroup::""")
          print("""::warning::::group::grup name\ngroup content\n::endgroup::""")
          print("""::group::::warning::warning title\ngroup content\n::endgroup::""")
          
      - shell: python
        run: |
          import rich
          import rich.rule
          import rich.text
          rich.print(rich.rule.Rule())

          print("::group:: Rich Group")
          rich.print(rich.rule.Rule())
          print("::endgroup::")

          console = rich.console.Console(force_terminal=True, width=100)

          print("::group:: Rich Group")
          console.print(rich.rule.Rule())
          print("::endgroup::")
          
          console.print("::group:: Rich Group")
          console.print(rich.rule.Rule())
          console.print("wrg")
          console.print("::endgroup::")
        
          text = rich.text.Text("::group:: ")
          text.append(rich.text.Text("Rich Group", style="red"))
          console.print(text)
          console.print(rich.rule.Rule())
          console.print("::endgroup::")

          from rich.console import Group
          g = Group(text, rich.rule.Rule(), "in group", "::endgroup::")
          console.print(g)

          text = rich.text.Text("::group:: ")
          text.append(rich.text.Text("Rich Group", style="red"))
          console.print(text)
          console.print(rich.rule.Rule())
          console.print("::endgroup::")
          
          
