on: workflow_dispatch
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: 'Download sdist and wheels artifacts'
        shell: bash
        run: |
          echo "::debug::This is a single-line debug."
          echo "::debug::Multi\nline\debug"
          echo "::notice file=app.js,line=1,col=5,endColumn=7,title=Notice Title::Notice message in one line"
          echo "::notice file=app.js,line=1,col=5,endColumn=7,title=Notice Title::Notice message in \n two lines"
          echo "::warning title=😬Warning Title::🙋Missing semicolon"
          echo "::error file=app.js,line=1,col=5,endColumn=7,title=Error Title::Missing semicolon"
          
          echo "::group::\033[1;38;2;255;255;255;48;2;150;0;170mMy title"
          echo "::debug::This is a single-line debug."
          echo "::debug::Multi\nline\debug"
          echo "::notice file=app.js,line=1,col=5,endColumn=7,title=Notice Title::Notice message in one line"
          echo "::notice file=app.js,line=1,col=5,endColumn=7,title=Notice Title::Notice message in \n two lines"
          echo "::warning file=app.js,line=1,col=5,endColumn=7,title=Warning Title::Missing semicolon"
          echo "::error file=app.js,line=1,col=5,endColumn=7,title=Error Title::Missing semicolon"
          echo "::endgroup::"
      - shell: python
        run: |
          print("::warning title=A Warning From Python::First line........rojgwgwr wrg wr gw rgwr gw rgw rgw g wrigjworijg wr gwirgj  worgjiw rog")
          print("::warning title=A Multiline Warning Title From Python::First line.\nSecond Line.\nThird Line.")
          print("::debug::A sinle line debug message from python")
          print("::debug::First Xline.\nSecond XLine.\n  XThird Line.\n    Fourth XLine")
          print("::debug::A sinle line debug message from python")
          print("::group::\033[1;38;2;255;255;255;48;2;150;0;170mMy title")
          print("Blah")
          print("::endgroup::)
