on: workflow_dispatch
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          pip install rich==13.8.1 ansi-sgr
          python -m rich
      - shell: python
        run: |
          from rich.console import Console
          from rich.panel import Panel
          from rich.syntax import Syntax
          
          yaml_syntax = """
          test: true
          examples:
              ex1: 1
              ex2: 2
          """
          code_panel = Panel(Syntax(yaml_syntax, lexer="yaml"))
          console = Console(force_terminal=True)
          console.print(code_panel)

          with console.capture() as capture:
              console.print(code_panel)
          str_output = capture.get()
          print(str_output)
          import ansi_sgr as sgr
          print(sgr.remove_sequence(str_output))

          multi_line = """First Line
            Second line indented
              Third line indented more"""

          print(multi_line)
          
          
