on: workflow_dispatch
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          pip install rich==13.8.1 ansi-sgr
          python -m rich
      - shell: python
        run: |
          from rich.console import Console
          from rich.panel import Panel
          from rich.syntax import Syntax
          
          yaml_syntax = """
          test: true
          examples:
              ex1: 1
              ex2: 2
          """
          code_panel = Panel(Syntax(yaml_syntax, lexer="yaml"))
          console = Console(force_terminal=True)
          print("Panel to Console:")
          console.print(code_panel)

          with console.capture() as capture:
              console.print(code_panel)
          str_output = capture.get()
          print(str_output)
          import ansi_sgr as sgr
          print(sgr.remove_sequence(str_output))

          multi_line = """First Line
          \033[48;2;39;40;34m  Second line indented
              Third line indented more"""

          print(multi_line)
          console.print(multi_line)

          synt = """╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
          │ \033[48;2;39;40;34m                                                                                                               \x1b[0m │
          │ \033[38;2;255;70;137;48;2;39;40;34mtest\033[0m\033[38;2;248;248;242;48;2;39;40;34m:\033[0m\033[38;2;248;248;242;48;2;39;40;34m \033[0m\033[48;2;39;40;34mtrue                                                                                                     \x1b[0m │
          │ \033[38;2;255;70;137;48;2;39;40;34mexamples\x1b[0m\033[38;2;248;248;242;48;2;39;40;34m:\033[0m\033[48;2;39;40;34m                                                                                                      \x1b[0m │
          │ \033[38;2;248;248;242;48;2;39;40;34m    \033[0m\033[38;2;255;70;137;48;2;39;40;34mex1\033[0m\033[38;2;248;248;242;48;2;39;40;34m:\033[0m\033[38;2;248;248;242;48;2;39;40;34m \033[0m\033[48;2;39;40;34m1                                                                                                     \x1b[0m │
          │ \033[38;2;248;248;242;48;2;39;40;34m    \033[0m\033[38;2;255;70;137;48;2;39;40;34mex2\033[0m\033[38;2;248;248;242;48;2;39;40;34m:\033[0m\033[38;2;248;248;242;48;2;39;40;34m \033[0m\033[48;2;39;40;34m2                                                                                                     \x1b[0m │
          │ \033[48;2;39;40;34m                                                                                                               \033[0m │
          ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯"""

          print(synt)
          console.print(synt)
          
          
