on: workflow_dispatch
jobs:
  test-ansi:
    runs-on: ubuntu-latest
    steps:
      - shell: python
        run: |
          print("The following must print a red line but it does not:")
          print("\033[48;2;255;0;0m                                  ")
          print("It only prints the line if it is not all spaces:")
          print("\033[48;2;255;0;0m               X                  ")
          print("Leading spaces are normally respected:")
          print("                                 X                  ")
          print("But not when they are envlosed by ANSI code:")
          print("\033[48;2;255;0;0m                       \033[0m  X ")

          
          synt = """╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
          │ \033[48;2;39;40;34m                                                                                                               \033[0m │
          │ \033[38;2;255;70;137;48;2;39;40;34mtest\033[0m\033[38;2;248;248;242;48;2;39;40;34m:\033[0m\033[38;2;248;248;242;48;2;39;40;34m \033[0m\033[48;2;39;40;34mtrue                                                                                                     \x1b[0m │
          │ \033[38;2;255;70;137;48;2;39;40;34mexamples\x1b[0m\033[38;2;248;248;242;48;2;39;40;34m:\033[0m\033[48;2;39;40;34m                                                                                                      \x1b[0m │
          │ \033[38;2;248;248;242;48;2;39;40;34m    \033[0m\033[38;2;255;70;137;48;2;39;40;34mex1\033[0m\033[38;2;248;248;242;48;2;39;40;34m:\033[0m\033[38;2;248;248;242;48;2;39;40;34m \033[0m\033[48;2;39;40;34m1                                                                                                     \x1b[0m │
          │ \033[38;2;248;248;242;48;2;39;40;34m    \033[0m\033[38;2;255;70;137;48;2;39;40;34mex2\033[0m\033[38;2;248;248;242;48;2;39;40;34m:\033[0m\033[38;2;248;248;242;48;2;39;40;34m \033[0m\033[48;2;39;40;34m2                                                                                                     \x1b[0m │
          │ \033[48;2;39;40;34m                                                                                                               \033[0m │
          ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯"""
          print(synt)
