on: workflow_dispatch
jobs:
  test-ansi:
    runs-on: ubuntu-latest
    steps:
      - shell: python
        run: |
          print("The following must print a red line but it does not:")
          print("\033[48;2;255;0;0m                                  ")
          print("It only prints the line if it is not all spaces:")
          print("\033[48;2;255;0;0m          X                       ")
          
