on: workflow_dispatch
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/setup-python@v5  # https://github.com/actions/setup-python
        id: setup1
        with:
          python-version: 3.9
      - uses: actions/setup-python@v5  # https://github.com/actions/setup-python
        id: setup2
        with:
          python-version: 3.12
      - env:
          OUT1__: ${{ toJSON(steps.setup1.outputs) }}
          OUT2__: ${{ toJSON(steps.setup1.outputs) }}
        shell: bash
        run: |
          echo $OUT1__
          echo $OUT2__
      - run: |
          ${{ steps.setup1.outputs.python-path }} --version
      - run: |
          ${{ steps.setup1.outputs.python-path }} -m pip --version
          ${{ steps.setup1.outputs.python-path }} -m venv v_env
          find v_env
